import Foundation

/// A transcribed word aligned to the original source audio timeline.
public struct TranscribedWord: Codable, Sendable {
    /// Word start time in the original audio context.
    public let startTime: Duration
    /// Word end time in the original audio context.
    public let endTime: Duration
    /// Word text.
    public let text: String

    /// Creates a transcribed word.
    public init(startTime: Duration, endTime: Duration, text: String) {
        self.startTime = startTime
        self.endTime = endTime
        self.text = text
    }

    private enum CodingKeys: String, CodingKey {
        case startTime
        case endTime
        case text
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        startTime = DurationCodec.decode(try container.decode(Double.self, forKey: .startTime))
        endTime = DurationCodec.decode(try container.decode(Double.self, forKey: .endTime))
        text = try container.decode(String.self, forKey: .text)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(DurationCodec.encode(startTime), forKey: .startTime)
        try container.encode(DurationCodec.encode(endTime), forKey: .endTime)
        try container.encode(text, forKey: .text)
    }
}

/// A transcribed line aligned to the original source audio timeline.
public struct TranscribedLine: Codable, Sendable {
    /// Source audio segment index that produced this line.
    public let segmentIndex: Int
    /// Line start time in the original audio context.
    public let startTime: Duration
    /// Line end time in the original audio context.
    public let endTime: Duration
    /// Line text.
    public let text: String
    /// Ordered words belonging to the line.
    public let words: [TranscribedWord]

    /// Creates a transcribed line.
    public init(segmentIndex: Int, startTime: Duration, endTime: Duration, text: String, words: [TranscribedWord]) {
        self.segmentIndex = segmentIndex
        self.startTime = startTime
        self.endTime = endTime
        self.text = text
        self.words = words
    }

    private enum CodingKeys: String, CodingKey {
        case segmentIndex
        case startTime
        case endTime
        case text
        case words
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        segmentIndex = try container.decode(Int.self, forKey: .segmentIndex)
        startTime = DurationCodec.decode(try container.decode(Double.self, forKey: .startTime))
        endTime = DurationCodec.decode(try container.decode(Double.self, forKey: .endTime))
        text = try container.decode(String.self, forKey: .text)
        words = try container.decode([TranscribedWord].self, forKey: .words)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(segmentIndex, forKey: .segmentIndex)
        try container.encode(DurationCodec.encode(startTime), forKey: .startTime)
        try container.encode(DurationCodec.encode(endTime), forKey: .endTime)
        try container.encode(text, forKey: .text)
        try container.encode(words, forKey: .words)
    }
}

/// Transcription result generated by ``AudioTranscriber``.
public struct AudioTranscriberModel: Codable, Sendable {
    /// Source audio duration.
    public let sourceAudioDuration: Duration
    /// Transcribed lines in source-time order.
    public let lines: [TranscribedLine]

    /// Creates a transcription result.
    public init(sourceAudioDuration: Duration, lines: [TranscribedLine]) {
        self.sourceAudioDuration = sourceAudioDuration
        self.lines = lines
    }

    private enum CodingKeys: String, CodingKey {
        case sourceAudioDuration
        case lines
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        sourceAudioDuration = DurationCodec.decode(try container.decode(Double.self, forKey: .sourceAudioDuration))
        lines = try container.decode([TranscribedLine].self, forKey: .lines)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(DurationCodec.encode(sourceAudioDuration), forKey: .sourceAudioDuration)
        try container.encode(lines, forKey: .lines)
    }
}
