import Foundation

/// A single audio segment produced by ``SegmentAudio``.
public struct AudioSegment: Codable, Sendable {
    /// 1-based index representing the segment order.
    public let index: Int
    /// Segment start time in `{seconds}.{milliseconds}` format.
    public let startTime: String
    /// Segment end time in `{seconds}.{milliseconds}` format.
    public let endTime: String
    /// Full output file path for the segment.
    public let filePath: String

    /// Creates an audio segment record.
    ///
    /// - Parameters:
    ///   - index: 1-based segment order.
    ///   - startTime: Segment start time in `{seconds}.{milliseconds}` format.
    ///   - endTime: Segment end time in `{seconds}.{milliseconds}` format.
    ///   - filePath: Full output file path for the segment.
    public init(index: Int, startTime: String, endTime: String, filePath: String) {
        self.index = index
        self.startTime = startTime
        self.endTime = endTime
        self.filePath = filePath
    }
}

/// Segmentation output generated by ``SegmentAudio``.
public struct SegmentAudioResult: Codable, Sendable {
    /// Source audio duration.
    public let sourceAudioDuration: Duration
    /// Ordered non-silent segments.
    public let segments: [AudioSegment]

    /// Creates a segmentation result.
    ///
    /// - Parameters:
    ///   - sourceAudioDuration: Source audio duration.
    ///   - segments: Ordered non-silent segments.
    public init(sourceAudioDuration: Duration, segments: [AudioSegment]) {
        self.sourceAudioDuration = sourceAudioDuration
        self.segments = segments
    }
}
