import Foundation

/// A transcribed word aligned to the original source audio timeline.
public struct TranscribedWord: Codable, Sendable {
    /// Word start time in the original audio context.
    public let startTime: Duration
    /// Word end time in the original audio context.
    public let endTime: Duration
    /// Word text.
    public let text: String

    /// Creates a transcribed word.
    public init(startTime: Duration, endTime: Duration, text: String) {
        self.startTime = startTime
        self.endTime = endTime
        self.text = text
    }
}

/// A transcribed line aligned to the original source audio timeline.
public struct TranscribedLine: Codable, Sendable {
    /// Line start time in the original audio context.
    public let startTime: Duration
    /// Line end time in the original audio context.
    public let endTime: Duration
    /// Line text.
    public let text: String
    /// Ordered words belonging to the line.
    public let words: [TranscribedWord]

    /// Creates a transcribed line.
    public init(startTime: Duration, endTime: Duration, text: String, words: [TranscribedWord]) {
        self.startTime = startTime
        self.endTime = endTime
        self.text = text
        self.words = words
    }
}

/// Transcription result generated by ``TranscribeAudio``.
public struct TranscribeAudioResult: Codable, Sendable {
    /// Source audio duration.
    public let sourceAudioDuration: Duration
    /// Transcribed lines in source-time order.
    public let lines: [TranscribedLine]

    /// Creates a transcription result.
    public init(sourceAudioDuration: Duration, lines: [TranscribedLine]) {
        self.sourceAudioDuration = sourceAudioDuration
        self.lines = lines
    }
}
