import Foundation

/// A single audio segment produced by ``AudioSegmenter``.
public struct AudioSegment: Codable, Sendable {
    /// 1-based index representing the segment order.
    public let index: Int
    /// Segment start time in `{seconds}.{milliseconds}` format.
    public let startTime: String
    /// Segment end time in `{seconds}.{milliseconds}` format.
    public let endTime: String

    /// Creates an audio segment record.
    ///
    /// - Parameters:
    ///   - index: 1-based segment order.
    ///   - startTime: Segment start time in `{seconds}.{milliseconds}` format.
    ///   - endTime: Segment end time in `{seconds}.{milliseconds}` format.
    public init(index: Int, startTime: String, endTime: String) {
        self.index = index
        self.startTime = startTime
        self.endTime = endTime
    }

    /// Builds the expected segment file URL from a source URL and segment index.
    ///
    /// If `sourceURL` points to a file, the segment inherits that file extension and directory.
    /// If `sourceURL` points to a directory, the segment is generated in that directory with `.wav` extension.
    ///
    /// - Parameters:
    ///   - sourceURL: Source URL used as the directory/extension template.
    ///   - index: 1-based segment index.
    /// - Returns: The expected segment file URL.
    public static func segmentFileURL(from sourceURL: URL, index: Int) -> URL {
        let directoryURL: URL
        let fileExtension: String

        if sourceURL.isDirectory {
            directoryURL = sourceURL
            fileExtension = "wav"
        } else {
            directoryURL = sourceURL.deletingLastPathComponent()
            fileExtension = sourceURL.pathExtension.isEmpty ? "wav" : sourceURL.pathExtension
        }

        let fileName = "vocal-segment-\(String(format: "%04d", index)).\(fileExtension)"
        return directoryURL.appendingPathComponent(fileName)
    }
}

/// Segmentation output generated by ``AudioSegmenter``.
public struct AudioSegmenterModel: Codable, Sendable {
    /// Source audio duration.
    public let sourceAudioDuration: Duration
    /// Ordered non-silent segments.
    public let segments: [AudioSegment]

    /// Creates a segmentation result.
    ///
    /// - Parameters:
    ///   - sourceAudioDuration: Source audio duration.
    ///   - segments: Ordered non-silent segments.
    public init(sourceAudioDuration: Duration, segments: [AudioSegment]) {
        self.sourceAudioDuration = sourceAudioDuration
        self.segments = segments
    }

    private enum CodingKeys: String, CodingKey {
        case sourceAudioDuration
        case segments
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        sourceAudioDuration = DurationCodec.decode(try container.decode(Double.self, forKey: .sourceAudioDuration))
        segments = try container.decode([AudioSegment].self, forKey: .segments)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(DurationCodec.encode(sourceAudioDuration), forKey: .sourceAudioDuration)
        try container.encode(segments, forKey: .segments)
    }
}
